labels_to_circle_params:
  ci/1:
    parameter: test_1
    default_true_on:
      branches:
        - master
        - ci-all/*
      tags:
        - v[0-9]+(\.[0-9]+)*-rc[0-9]+
  ci/2:
    parameter: test_2
  ci/3:
    parameter: test_3
