version: 2.1

jobs:
  simple_job:
    docker:
      - image: circleci/python:3
    steps:
      - run:
          name: This should fail
          command: exit 1
      - run:
          when: always
          name: This should run afterwards to simulate cleanup
          command: echo "I was runnning"

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - simple_job
