version: 2.1

jobs:
  simple_job:
    machine: true
    steps:
      - run:
          name: This should run only after manual approval
          command: echo "I was runnning"

workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - simple_job:
          name: simple1
      - blank_job:
          name: simple2
          type: approval
          requires:
            - simple1
      - simple_job:
          name: simple3
          requires:
            - simple2
